Fixed type error in snapshot command
```
Traceback (most recent call last):
  File "/usr/bin/bahub-origin", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/bahub/__init__.py", line 89, in main
    raise e
  File "/usr/lib/python3.6/site-packages/bahub/__init__.py", line 85, in main
    app.run_controller(parsed.options[0], parsed.options[1], parsed.debug, parsed.options)
  File "/usr/lib/python3.6/site-packages/bahub/bahubapp/app.py", line 102, in run_controller
    response = controller.perform(param)
  File "/usr/lib/python3.6/site-packages/bahub/bahubapp/controller/snapshot.py", line 17, in perform
    result = self._perform_recovery(name, plan)
  File "/usr/lib/python3.6/site-packages/bahub/bahubapp/controller/snapshot.py", line 30, in _perform_recovery
    self._client
TypeError: __init__() missing 1 required positional argument: 'notifier'
```